version: "3.2"
services:
  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - firefly_iii_net

  portainer:
    image: portainer/portainer
    restart: always
    container_name: "portainer"
#Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    command: --templates http://templates/templates.json
    ports:
      - "9000:9000"
    networks:
      - firefly_iii_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

  watchtower:
    image: v2tec/watchtower
    container_name: "watchtower"
    command: --schedule "0 0 4 * * *" --cleanup pv2tec/watchtower portainer/templates portainer/portainer jc5x/firefly-iii postgres:10
    networks:
      - firefly_iii_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  firefly_iii_app: 
    environment: 
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=password
      - FF_APP_KEY=GdsI8dVHEmBW!T5CV4lz1Np3Bx4xd7&d # enter your own APP key, has to be exactly 32 chars!!!!
      - FF_APP_ENV=local
      - FF_DB_CONNECTION=pgsql
      - TZ=America/Chicago
      - APP_LOG_LEVEL=debug
            
    image: jc5x/firefly-iii
    container_name: firefly
    restart: always
    links: 
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "80:80"
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
        
  firefly_iii_db: 
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=firefly
    image: "postgres:10"
    container_name: fireflydb
    restart: always
    networks: 
      - firefly_iii_net
    volumes: 
      - "firefly_iii_db:/var/lib/postgresql/data"

networks:
  firefly_iii_net: 
    driver: bridge
 
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
  portainer_data: ~
  shared: ~
  



